### ISSUE TITLE
User Endpoint

### ISSUE THREAD

**Issue by ygina** [battlecode/battlecode19#19]
- [ ] `POST /user/confirm`
In: {registration_token}

- [ ] `POST /user/reset_password`
In: {email}

- [ ] `PATCH /user/reset_password`
In: {reset_token, new_password}

- [ ] `PATCH /user/{userid}/change_password`
Auth: current user only
In: {old_password, new_password}

- [ ] `PATCH /user/{userid}/upload`
Auth: current user only
In: {op (avatar/resume), bytes}

**Comment by joshuagruenstein** [comment]
we have this.
