### ISSUE TITLE
Page not found at /

### ISSUE THREAD

**Issue by tyleralgigi** [battlecode/battlecode19#75]
After following the read me and installing everything in the requirements.txt. I proceeded to run the server and when I open a web browser and go to http://127.0.0.1:8000/ I get a 404 error in my browser that looks like:
```
Request Method: | GET
-- | --
http://127.0.0.1:8000/
Using the URLconf defined in urls, Django tried these URL patterns, in this order:
__debug__/
auth/token/
auth/token/refresh/
auth/token/verify/
api/
admin/
docs/
api/password_reset/
The empty path didn't match any of these.
```

and in my terminal I get: 

> Not Found: /
> [05/Feb/2019 00:24:55] "GET / HTTP/1.1" 404 2700

Any help would be appreciated, Im really stuck...

**Comment by tyleralgigi** [comment]
/api/ brings me to a 404 erros but this time it says:
```
HTTP 401 Unauthorized
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
WWW-Authenticate: Bearer realm="api"

{
    "detail": "Authentication credentials were not provided."
}

```
/admin/ brings me to a login page but I dont know where I get the login information from or where I sign up.
/docs/ brings me to a Your API page. I do not know where to proceed from here. I am trying to run the Battlecode game itself, but Im not sure if Im in the right place?

**Comment by npfoss** [comment]
If you're just trying to run a game, try the instructions and example code here: https://github.com/npfoss/examplefuncsplayer

And view the match file with this viewer: https://github.com/hgarrereyn/Clairvoyance
